name: multi_job_wf
on: push

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v4

      - name: install cowsay
        run: |
            sudo apt-get update
            sudo apt-get install cowsay -y

      - name: Generate ASCII Dragon
        run: cowsay -f dragon "Run for cover, I am a DRAGON... RAWR" >> dragon.txt

      - name: Upload dragon file
        uses: actions/upload-artifact@v6
        with:
          name: dragon-text-file
          path: dragon.txt

  test_job:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
      - name: download dragon file
        uses: actions/download-artifact@v6
        with:
          name: dragon-text-file

      - name: Verify dragon.txt
        run: grep -i "dragon" dragon.txt

  deploy_job:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: download dragon file
        uses: actions/download-artifact@v6
        with:
          name: dragon-text-file

      - name: Display dragon.txt
        run: cat dragon.txt

      - name: Simulate deployment
        run: echo "Deploying dragon.txt"

# By default, GitHub Actions runs jobs in parallel on separate VMs. 
# Since there’s no shared filesystem or enforced order, downstream jobs may start before the build completes.

# Solution: Needs
# Use needs: build_job so that test_job waits for build_job to finish successfully

# Each job runs on a clean virtual machine. 
# If you don’t persist files between jobs, later steps will fail.

# Solution: share files and data between jobs using artifacts and workspaces
# To pass files from build_job_1 to downstream jobs, 
# use the actions/upload-artifact and actions/download-artifact actions.

      
    