name: My first workflow # name of the workflow

on: push # Trigger

jobs:
    first_job: # Can have multiple jobs. Jobs can run in parallel or sequence
        runs-on: ubuntu-latest
        steps: # Steps of a job always run sequentially
            - name: Welcome message
              run: echo "My first actions job"
            - name: List File # This will fail without checking out the code
              run: ls -lah 
            - name: Read file
              run: cat README.md


